/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ReadRootGet$Params as ReadRootGet$Params } from './fn/health/read-root-get'
export { readRootGet as readRootGet } from './fn/health/read-root-get'
export type { ReadVersionVersionGet$Params as ReadVersionVersionGet$Params } from './fn/health/read-version-version-get'
export { readVersionVersionGet as readVersionVersionGet } from './fn/health/read-version-version-get'
