"""Airflow dag_run_id conventions for a dataset (integrity link).

Single source of truth for how run ids are built and matched:
- initial staging run:  "<integrity_link_id>"
- staging rerun:        "<integrity_link_id>_<timestamp>"
- manual process run:   "<integrity_link_id>_<timestamp>_manual"
- scheduled process run: "<integrity_link_id>_<ts_nodash>" — generated by the
  ingestion DAG in apps/elt/dags/process-dag-generator.py, which cannot import
  this module; keep both in sync.

The LIKE helpers feed Airflow's run_id_pattern (SQL LIKE) parameter. The '_'
separator is not escaped — it doubles as a single-char wildcard, which is
harmless here because integrity link ids are fixed-length UUIDs, so no other
dataset's run id can match.
"""

MANUAL_RUN_SUFFIX = "_manual"

__all__ = [
    "MANUAL_RUN_SUFFIX",
    "extract_integrity_link_id",
    "is_manual_process_run",
    "make_initial_staging_run_id",
    "make_manual_process_run_id",
    "make_staging_rerun_id",
    "process_run_like",
    "process_run_prefix",
    "staging_run_like",
    "staging_run_prefix",
]


def make_initial_staging_run_id(integrity_link_id: str) -> str:
    """Run id of the first staging run of a dataset."""
    return integrity_link_id


def make_staging_rerun_id(integrity_link_id: str, timestamp: int) -> str:
    """Run id of a staging rerun (reconfiguration)."""
    return f"{integrity_link_id}_{timestamp}"


def make_manual_process_run_id(integrity_link_id: str, timestamp: int) -> str:
    """Run id of a user-triggered process run."""
    return f"{integrity_link_id}_{timestamp}{MANUAL_RUN_SUFFIX}"


def is_manual_process_run(dag_run_id: str) -> bool:
    """True for user-triggered process runs, False for scheduled ones."""
    return dag_run_id.endswith(MANUAL_RUN_SUFFIX)


def extract_integrity_link_id(dag_run_id: str) -> str:
    """Integrity link id encoded at the start of any run id."""
    return dag_run_id.split("_")[0]


def staging_run_prefix(integrity_link_id: str) -> str:
    """startswith() prefix matching all staging runs of a dataset.

    No trailing '_': the first staging run id is exactly the integrity link id.
    """
    return integrity_link_id


def process_run_prefix(integrity_link_id: str) -> str:
    """startswith() prefix matching all process runs of a dataset."""
    return f"{integrity_link_id}_"


def staging_run_like(integrity_link_id: str) -> str:
    """SQL LIKE pattern matching all staging runs of a dataset."""
    return f"{integrity_link_id}%"


def process_run_like(integrity_link_id: str) -> str:
    """SQL LIKE pattern matching all process runs of a dataset."""
    return f"{integrity_link_id}_%"
