from enum import Enum

from typing import TypedDict
from pydantic import BaseModel, Field, field_validator


class Thesaurus(TypedDict):
    title: str
    kw: list[tuple[str, str]]


class KwStrategy(Enum):
    PROMPTED = 1    # convert model to system prompt
    STRUCTURED = 2  # structured llm output with all keywords at once
    STAGED = 3      # 2-staged keyword selection: first choose thesaurus then select contained KWs


class LlmMetadataMode(str, Enum):
    REGENERATE = "regenerate"
    REWRITE = "rewrite"


class LlmMetadataDataSource(str, Enum):
    STAGING = "staging"
    FINAL = "final"


class AttributeInfo(BaseModel):
    """Description of a single dataset attribute/column.

    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    name: str = Field(max_length=256, description="Column name")
    type: str = Field(
        max_length=256, description="ISO 19110 type (e.g. integer, string (50), GM_Point)"
    )
    description: str = Field(
        max_length=256, description="Human-readable description of the column in French"
    )


class TemporalExtent(BaseModel):
    """Temporal extent of the dataset, either a single instant or a period.

    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    type: str = Field(
        max_length=128,
        description=(
            "Either 'instant' (single date/time) or 'period' (date range). "
            "Use 'unknown' if no temporal information can be inferred."
        ),
    )
    begin: str | None = Field(
        default=None,
        max_length=64,
        description=(
            "Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). "
            "Required when type='period', optional when type='instant'."
        ),
    )
    end: str | None = Field(
        default=None,
        max_length=64,
        description=(
            "End date/time in ISO 8601 format. Required when type='period'. "
            "Use null if open-ended or unknown."
        ),
    )
    instant: str | None = Field(
        default=None,
        max_length=64,
        description="Date/time in ISO 8601 format when type='instant'.",
    )


class GeneratedMetadata(BaseModel):
    """Structured metadata generated by the LLM.

    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    title: str = Field(
        max_length=256, description="A concise, human-readable title for the dataset"
    )
    abstract: str = Field(
        max_length=2048, description="A clear description of the dataset contents and purpose"
    )
    keywords: list[str] = Field(description="Relevant thematic keywords for the dataset")
    topic_categories: list[str] = Field(
        description=(
            "One or more ISO 19115 topic category codes that best describe the dataset "
            "(e.g. ['transportation', 'planningCadastre'])"
        )
    )
    # -- NB. deactivated for now, but keep the field in the model for future use.
    # attribute_descriptions: list[AttributeInfo] | None = Field(
    #    description="Description of each attribute/column of the dataset"
    # )
    attribute_descriptions: None = Field(default=None, description="")
    temporal_extent: TemporalExtent | None = Field(
        default=None,
        description=(
            "Temporal extent of the dataset inferred from column names, sample data, or table name. "
            "Set to null if no temporal information can be found."
        ),
    )

    @field_validator("keywords")
    @classmethod
    def validate_keywords_total_length(cls, value: list[str]) -> list[str]:
        # Limit the combined keywords text length (including ", " separators).
        if len(", ".join(value)) > 1024:
            raise ValueError("keywords must not exceed 1024 characters in total")
        return value

    @field_validator("topic_categories")
    @classmethod
    def validate_topic_categories_total_length(cls, value: list[str]) -> list[str]:
        # Limit the combined topic categories text length (including ", " separators).
        if len(", ".join(value)) > 512:
            raise ValueError("topic_categories must not exceed 512 characters in total")
        return value
