"""AI-powered metadata generation using LangChain."""

import logging
from pathlib import Path
from typing import Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field

from ai.utils import load_prompt

logger = logging.getLogger(__name__)


def _format_sample(sample_rows: list[dict[str, object]] | None) -> str:
    """Format sample rows as a compact CSV-like string for the prompt."""
    if not sample_rows:
        return "not available"
    lines = []
    headers = list(sample_rows[0].keys())
    lines.append(", ".join(str(h) for h in headers))
    for row in sample_rows:
        lines.append(", ".join(str(row.get(h, "")) for h in headers))
    return "\n".join(lines)


class GeneratedMetadata(BaseModel):
    """Structured metadata generated by the LLM."""

    title: str = Field(description="A concise, human-readable title for the dataset")
    abstract: str = Field(description="A clear description of the dataset contents and purpose")
    keywords: list[str] = Field(description="Relevant thematic keywords for the dataset")
    topic_categories: list[str] = Field(
        description=(
            "One or more ISO 19115 topic category codes that best describe the dataset "
            "(e.g. ['transportation', 'planningCadastre'])"
        )
    )


def generate_metadata(
    table_name: str,
    column_names: list[str],
    llm: BaseChatModel,
    title: str | None = None,
    extra_context: dict[str, Any] | None = None,
    sample_rows: list[dict[str, object]] | None = None,
    bbox: str | None = None,
    priority_keywords: list[str] | None = None,
    priority_topic_categories: list[str] | None = None,
    system_prompt_path: Path | str | None = None,
    human_prompt_path: Path | str | None = None,
) -> GeneratedMetadata:
    """Generate dataset metadata using an LLM.

    All configuration (LLM instance, prompt paths) must be passed explicitly.

    Args:
        table_name: Name of the final PostGIS table
        column_names: List of column names in the table
        llm: LangChain chat model instance to use
        title: Human-readable title already chosen by the user (optional)
        extra_context: Any additional context to pass to the prompt (optional)
        sample_rows: Up to 5 sample rows from the table for richer inference (optional)
        bbox: Bounding box string "minx, miny, maxx, maxy" for geographic context (optional)
        priority_keywords: Preferred keywords to use when relevant (optional)
        priority_topic_categories: Preferred ISO 19115 topic categories to favour (optional)
        system_prompt_path: Path to a custom system prompt file (optional)
        human_prompt_path: Path to a custom human prompt file (optional)

    Returns:
        GeneratedMetadata with title, abstract, keywords and topic_categories
    """
    parser = PydanticOutputParser(pydantic_object=GeneratedMetadata)

    system_prompt = load_prompt("metadata_system.txt", system_prompt_path)
    human_prompt = load_prompt("metadata_human.txt", human_prompt_path)

    prompt = ChatPromptTemplate.from_messages(
        [("system", system_prompt), ("human", human_prompt)]
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser

    result = chain.invoke(
        {
            "table_name": table_name,
            "title": title or table_name,
            "columns": ", ".join(column_names),
            "sample": _format_sample(sample_rows),
            "bbox": bbox or "not available",
            "priority_keywords": (
                "- Preferred keywords (use these if relevant): " + ", ".join(priority_keywords)
                if priority_keywords
                else ""
            ),
            "priority_topics": (
                "- Preferred topic categories (favour these if they fit): "
                + ", ".join(priority_topic_categories)
                if priority_topic_categories
                else ""
            ),
            "extra_context": (f"Additional context: {extra_context}" if extra_context else ""),
        }
    )

    logger.info(
        f"Generated metadata for '{table_name}': "
        f"title={result.title}, "
        f"abstract={result.abstract}, "
        f"keywords={result.keywords}, topics={result.topic_categories}"
    )

    return result
