"""AI-powered metadata generation using LangChain."""

import logging
from pathlib import Path
from typing import Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field

from ai.utils import load_prompt

logger = logging.getLogger(__name__)


class GeneratedMetadata(BaseModel):
    """Structured metadata generated by the LLM."""

    abstract: str = Field(description="A clear description of the dataset contents and purpose")
    keywords: list[str] = Field(description="Relevant thematic keywords for the dataset")
    topic_category: str = Field(
        description="ISO 19115 topic category (e.g. 'environment', 'transportation', 'boundaries')"
    )


def generate_metadata(
    table_name: str,
    column_names: list[str],
    llm: BaseChatModel,
    title: str | None = None,
    extra_context: dict[str, Any] | None = None,
    system_prompt_path: Path | str | None = None,
    human_prompt_path: Path | str | None = None,
) -> GeneratedMetadata:
    """Generate dataset metadata using an LLM.

    All configuration (LLM instance, prompt paths) must be passed explicitly.

    Args:
        table_name: Name of the final PostGIS table
        column_names: List of column names in the table
        llm: LangChain chat model instance to use
        title: Human-readable title already chosen by the user (optional)
        extra_context: Any additional context to pass to the prompt (optional)
        system_prompt_path: Path to a custom system prompt file (optional)
        human_prompt_path: Path to a custom human prompt file (optional)

    Returns:
        GeneratedMetadata with abstract, keywords and topic_category
    """
    parser = PydanticOutputParser(pydantic_object=GeneratedMetadata)

    system_prompt = load_prompt("metadata_system.txt", system_prompt_path)
    human_prompt = load_prompt("metadata_human.txt", human_prompt_path)

    prompt = ChatPromptTemplate.from_messages(
        [("system", system_prompt), ("human", human_prompt)]
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser

    result = chain.invoke(
        {
            "table_name": table_name,
            "title": title or table_name,
            "columns": ", ".join(column_names),
            "extra_context": (f"Additional context: {extra_context}" if extra_context else ""),
        }
    )

    logger.info(
        f"Generated metadata for '{table_name}': "
        f"keywords={result.keywords}, topic={result.topic_category}"
    )

    return result
