from enum import Enum

from pydantic import BaseModel, Field, field_validator


class LlmMetadataMode(str, Enum):
    REGENERATE = "regenerate"
    REWRITE = "rewrite"


class LlmMetadataDataSource(str, Enum):
    STAGING = "staging"
    FINAL = "final"


class AttributeInfo(BaseModel):
    """Description of a single dataset attribute/column.

    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    name: str = Field(max_length=256, description="Column name")
    type: str = Field(
        max_length=256, description="ISO 19110 type (e.g. integer, string (50), GM_Point)"
    )
    description: str = Field(
        max_length=256, description="Human-readable description of the column in French"
    )


class TemporalExtent(BaseModel):
    """Temporal extent of the dataset, either a single instant (no end) or a period.
    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    start: str | None = Field(
        default=None,
        max_length=64,
        description=(
            "Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). "
            "Start of period. "
            "Single date of Validity in case of instant without duration."
        ),
    )
    end: str | None = Field(
        default=None,
        max_length=64,
        description=(
            "End date/time in ISO 8601 format. "
            "End of time period. "
            "IMPORTANT: end must be null for an insant Datestamp without duration."
        ),
    )


class GeneratedMetadata(BaseModel):
    """Structured metadata generated by the LLM.

    Note: string max_length limits are intentionally added to help control LLM token usage.
    """

    title: str = Field(
        max_length=256, description="A concise, human-readable title for the dataset"
    )
    abstract: str = Field(
        max_length=2048,
        description=(
            "A clear description of the dataset contents and purpose, "
            "written in Markdown syntax (e.g. **bold** on key terms)"
        ),
    )
    keywords: list[str] = Field(description="Relevant thematic keywords for the dataset")
    topic_categories: list[str] = Field(
        description=(
            "One or more ISO 19115 topic category codes that best describe the dataset "
            "(e.g. ['transportation', 'planningCadastre'])"
        )
    )
    # -- NB. deactivated for now, but keep the field in the model for future use.
    # attribute_descriptions: list[AttributeInfo] | None = Field(
    #    description="Description of each attribute/column of the dataset"
    # )
    attribute_descriptions: list[AttributeInfo] | None = Field(default=None, description="")
    temporal_extent: TemporalExtent | None = Field(
        default=None,
        description=(
            "Temporal extent of the dataset inferred from column names, sample data, or table name. "
            "Set to null if no temporal information can be found."
        ),
    )

    @field_validator("keywords")
    @classmethod
    def validate_keywords_total_length(cls, value: list[str]) -> list[str]:
        # Limit the combined keywords text length (including ", " separators).
        if len(", ".join(value)) > 1024:
            raise ValueError("keywords must not exceed 1024 characters in total")
        return value

    @field_validator("topic_categories")
    @classmethod
    def validate_topic_categories_total_length(cls, value: list[str]) -> list[str]:
        # Limit the combined topic categories text length (including ", " separators).
        if len(", ".join(value)) > 512:
            raise ValueError("topic_categories must not exceed 512 characters in total")
        return value
