"""AI-powered metadata generation using LangChain."""

import logging
from pathlib import Path
from typing import Any

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import ChatPromptTemplate
from pydantic import BaseModel, Field

from ai.utils import load_prompt

logger = logging.getLogger(__name__)


def _format_sample(sample_rows: list[dict[str, object]] | None) -> str:
    """Format sample rows as a compact CSV-like string for the prompt (values only, no headers)."""
    if not sample_rows:
        return "not available"
    headers = list(sample_rows[0].keys())
    lines = [", ".join(str(row.get(h, "")) for h in headers) for row in sample_rows]
    return "\n".join(lines)


class AttributeInfo(BaseModel):
    """Description of a single dataset attribute/column."""

    name: str = Field(description="Column name")
    type: str = Field(description="ISO 19110 type (e.g. integer, string (50), GM_Point)")
    description: str = Field(description="Human-readable description of the column in French")


class TemporalExtent(BaseModel):
    """Temporal extent of the dataset, either a single instant or a period."""

    type: str = Field(
        description=(
            "Either 'instant' (single date/time) or 'period' (date range). "
            "Use 'unknown' if no temporal information can be inferred."
        )
    )
    begin: str | None = Field(
        default=None,
        description=(
            "Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). "
            "Required when type='period', optional when type='instant'."
        ),
    )
    end: str | None = Field(
        default=None,
        description=(
            "End date/time in ISO 8601 format. Required when type='period'. "
            "Use null if open-ended or unknown."
        ),
    )
    instant: str | None = Field(
        default=None,
        description="Date/time in ISO 8601 format when type='instant'.",
    )


class GeneratedMetadata(BaseModel):
    """Structured metadata generated by the LLM."""

    title: str = Field(description="A concise, human-readable title for the dataset")
    abstract: str = Field(description="A clear description of the dataset contents and purpose")
    keywords: list[str] = Field(description="Relevant thematic keywords for the dataset")
    topic_categories: list[str] = Field(
        description=(
            "One or more ISO 19115 topic category codes that best describe the dataset "
            "(e.g. ['transportation', 'planningCadastre'])"
        )
    )
    attribute_descriptions: list[AttributeInfo] = Field(
        description="Description of each attribute/column of the dataset"
    )
    temporal_extent: TemporalExtent | None = Field(
        default=None,
        description=(
            "Temporal extent of the dataset inferred from column names, sample data, or table name. "
            "Set to null if no temporal information can be found."
        ),
    )


def generate_metadata(
    table_name: str,
    column_names: list[str],
    llm: BaseChatModel,
    column_types: dict[str, str] | None = None,
    title: str | None = None,
    extra_context: dict[str, Any] | None = None,
    sample_rows: list[dict[str, object]] | None = None,
    bbox: str | None = None,
    keywords: list[str] | None = None,
    priority_topic_categories: list[str] | None = None,
    system_prompt_path: Path | str | None = None,
    human_prompt_path: Path | str | None = None,
    mode: str = "regenerate",
    current_values: dict[str, Any] | None = None,
) -> GeneratedMetadata:
    """Generate dataset metadata using an LLM.

    All configuration (LLM instance, prompt paths) must be passed explicitly.

    Args:
        table_name: Name of the final PostGIS table
        column_names: List of column names in the table
        llm: LangChain chat model instance to use
        column_types: Mapping of column name → SQL type string (optional)
        title: Human-readable title already chosen by the user (optional)
        extra_context: Any additional context to pass to the prompt (optional)
        sample_rows: Up to 5 sample rows from the table for richer inference (optional)
        bbox: Bounding box string "minx, miny, maxx, maxy" for geographic context (optional)
        keywords: Preferred keywords to use when relevant (optional)
        priority_topic_categories: Preferred ISO 19115 topic categories to favour (optional)
        system_prompt_path: Path to a custom system prompt file (optional)
        human_prompt_path: Path to a custom human prompt file (optional)

    Returns:
        GeneratedMetadata with title, abstract, keywords and topic_categories
    """
    parser = PydanticOutputParser(pydantic_object=GeneratedMetadata)

    system_prompt = load_prompt(system_prompt_path, default="metadata_system.md")
    human_prompt = load_prompt(human_prompt_path, default="metadata_human.md")

    prompt = ChatPromptTemplate.from_messages(
        [("system", system_prompt), ("human", human_prompt)]
    ).partial(format_instructions=parser.get_format_instructions())

    chain = prompt | llm | parser

    result = chain.invoke(
        {
            "title": (current_values.get("title") if current_values else None)
            or title
            or table_name,
            "columns_with_types": ", ".join(
                f"{n} ({column_types[n]})" if column_types and n in column_types else n
                for n in column_names
            ),
            "sample": _format_sample(sample_rows),
            "bbox": bbox or "not available",
            "current_abstract": (
                f"{current_values['abstract']}"
                if current_values and current_values.get("abstract")
                else ""
            ),
            "current_keywords": (
                f"{current_values['keywords']}"
                if current_values and current_values.get("keywords")
                else ""
            ),
            "current_topics": (
                f"{current_values['topics']}"
                if current_values and current_values.get("topics")
                else ""
            ),
            "keywords": (", ".join(keywords) if keywords else ""),
            "topics": (", ".join(priority_topic_categories) if priority_topic_categories else ""),
            "extra_context": (extra_context if extra_context else ""),
            "mode_instruction": (
                "REWRITE — improve, rephrase and enrich the existing values if provided above. "
                "Keep the meaning but make them clearer, more professional and more complete."
                if mode == "rewrite"
                else "REGENERATE — For title only, minor rewording allowed to integrate current_abstract location if provided. Other fields: no reformulation."
            ),
        }
    )

    logger.info(
        f"Generated metadata for '{table_name}': "
        f"title={result.title}, "
        f"abstract={result.abstract}, "
        f"keywords={result.keywords}, topics={result.topic_categories}"
    )

    return result
