/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface DagSuccessCallbackIngestionProcessDagSuccessPost$Params {
  /**
   * IntegrityLink ID
   */
  integrity_link_id: string

  /**
   * Final table name
   */
  final_table_name: string

  /**
   * PostgreSQL schema of the final table
   */
  target_schema?: string
}

export function dagSuccessCallbackIngestionProcessDagSuccessPost(
  http: HttpClient,
  rootUrl: string,
  params: DagSuccessCallbackIngestionProcessDagSuccessPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(
    rootUrl,
    dagSuccessCallbackIngestionProcessDagSuccessPost.PATH,
    'post'
  )
  if (params) {
    rb.query('integrity_link_id', params.integrity_link_id, {})
    rb.query('final_table_name', params.final_table_name, {})
    rb.query('target_schema', params.target_schema, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<any>
      })
    )
}

dagSuccessCallbackIngestionProcessDagSuccessPost.PATH =
  '/ingestion/process/dag_success'
