/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface DagFailureCallbackIngestionStagingDagFailurePost$Params {
  /**
   * IntegrityLink ID
   */
  integrity_link_id: string

  /**
   * DAG ID
   */
  dag_id: string

  /**
   * DAG run ID
   */
  dag_run_id: string

  /**
   * Failure reason from Airflow context
   */
  reason?: string | null
}

export function dagFailureCallbackIngestionStagingDagFailurePost(
  http: HttpClient,
  rootUrl: string,
  params: DagFailureCallbackIngestionStagingDagFailurePost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(
    rootUrl,
    dagFailureCallbackIngestionStagingDagFailurePost.PATH,
    'post'
  )
  if (params) {
    rb.query('integrity_link_id', params.integrity_link_id, {})
    rb.query('dag_id', params.dag_id, {})
    rb.query('dag_run_id', params.dag_run_id, {})
    rb.query('reason', params.reason, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<any>
      })
    )
}

dagFailureCallbackIngestionStagingDagFailurePost.PATH =
  '/ingestion/staging/dag_failure'
