/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface DeleteScheduleIngestionIntegrityLinkIntegrityLinkIdScheduleDelete$Params {
  integrity_link_id: string
}

export function deleteScheduleIngestionIntegrityLinkIntegrityLinkIdScheduleDelete(
  http: HttpClient,
  rootUrl: string,
  params: DeleteScheduleIngestionIntegrityLinkIntegrityLinkIdScheduleDelete$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<void>> {
  const rb = new requestBuilders(
    rootUrl,
    deleteScheduleIngestionIntegrityLinkIntegrityLinkIdScheduleDelete.PATH,
    'delete'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
  }

  return http
    .request(rb.build({ responseType: 'text', accept: '*/*', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return (r as HttpResponse<any>).clone({
          body: undefined
        }) as StrictHttpResponse<void>
      })
    )
}

deleteScheduleIngestionIntegrityLinkIntegrityLinkIdScheduleDelete.PATH =
  '/ingestion/integrity-link/{integrity_link_id}/schedule'
