/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { StagingMetadata } from '../../models/staging-metadata'
import { StagingMetadataResponse } from '../../models/staging-metadata-response'

export interface EditStagingMetadataIngestionStagingIntegrityLinkIdMetadataPut$Params {
  integrity_link_id: string
  body: StagingMetadata
}

export function editStagingMetadataIngestionStagingIntegrityLinkIdMetadataPut(
  http: HttpClient,
  rootUrl: string,
  params: EditStagingMetadataIngestionStagingIntegrityLinkIdMetadataPut$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<StagingMetadataResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    editStagingMetadataIngestionStagingIntegrityLinkIdMetadataPut.PATH,
    'put'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.body(params.body, 'application/json')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<StagingMetadataResponse>
      })
    )
}

editStagingMetadataIngestionStagingIntegrityLinkIdMetadataPut.PATH =
  '/ingestion/staging/{integrity_link_id}/metadata'
