/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { BodyEditStagingIngestionStagingIntegrityLinkIdPut } from '../../models/body-edit-staging-ingestion-staging-integrity-link-id-put'
import { StagingResponse } from '../../models/staging-response'

export interface EditStagingIngestionStagingIntegrityLinkIdPut$Params {
  integrity_link_id: string
  body: BodyEditStagingIngestionStagingIntegrityLinkIdPut
}

export function editStagingIngestionStagingIntegrityLinkIdPut(
  http: HttpClient,
  rootUrl: string,
  params: EditStagingIngestionStagingIntegrityLinkIdPut$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<StagingResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    editStagingIngestionStagingIntegrityLinkIdPut.PATH,
    'put'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.body(params.body, 'multipart/form-data')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<StagingResponse>
      })
    )
}

editStagingIngestionStagingIntegrityLinkIdPut.PATH =
  '/ingestion/staging/{integrity_link_id}'
