/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { StagingPreviewResponse } from '../../models/staging-preview-response'

export interface GetStagingPreviewIngestionStagingIntegrityLinkIdPreviewGet$Params {
  integrity_link_id: string

  /**
   * Number of rows to preview
   */
  limit?: number

  /**
   * CRS/projection (e.g., EPSG:4326)
   */
  projection?: string | null

  /**
   * Latitude column name
   */
  x_column?: string | null

  /**
   * Longitude column name
   */
  y_column?: string | null
}

export function getStagingPreviewIngestionStagingIntegrityLinkIdPreviewGet(
  http: HttpClient,
  rootUrl: string,
  params: GetStagingPreviewIngestionStagingIntegrityLinkIdPreviewGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<StagingPreviewResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    getStagingPreviewIngestionStagingIntegrityLinkIdPreviewGet.PATH,
    'get'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.query('limit', params.limit, {})
    rb.query('projection', params.projection, {})
    rb.query('x_column', params.x_column, {})
    rb.query('y_column', params.y_column, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<StagingPreviewResponse>
      })
    )
}

getStagingPreviewIngestionStagingIntegrityLinkIdPreviewGet.PATH =
  '/ingestion/staging/{integrity_link_id}/preview'
