/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { IntegrityLinkResponse } from '../../models/integrity-link-response'

export interface GetIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdGet$Params {
  integrity_link_id: string

  /**
   * Include the integrity_transformation field in the response
   */
  include_transformation?: boolean
}

export function getIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdGet(
  http: HttpClient,
  rootUrl: string,
  params: GetIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<IntegrityLinkResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    getIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdGet.PATH,
    'get'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.query('include_transformation', params.include_transformation, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<IntegrityLinkResponse>
      })
    )
}

getIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdGet.PATH =
  '/ingestion/integrity-link/{integrity_link_id}'
