/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { JoinableColumn } from '../../models/joinable-column'

export interface GetJoinableColumnsIngestionIntegrityLinksIntegrityLinkIdJoinableColumnsGet$Params {
  integrity_link_id: string
}

export function getJoinableColumnsIngestionIntegrityLinksIntegrityLinkIdJoinableColumnsGet(
  http: HttpClient,
  rootUrl: string,
  params: GetJoinableColumnsIngestionIntegrityLinksIntegrityLinkIdJoinableColumnsGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<JoinableColumn>>> {
  const rb = new requestBuilders(
    rootUrl,
    getJoinableColumnsIngestionIntegrityLinksIntegrityLinkIdJoinableColumnsGet.PATH,
    'get'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<JoinableColumn>>
      })
    )
}

getJoinableColumnsIngestionIntegrityLinksIntegrityLinkIdJoinableColumnsGet.PATH =
  '/ingestion/integrity-links/{integrity_link_id}/joinable-columns'
