/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { IntegrityLinkListResponse } from '../../models/integrity-link-list-response'
import { PublicAccess } from '../../models/public-access'
import { RecurrencePreset } from '../../models/recurrence-preset'

export interface ListIntegrityLinksIngestionIntegrityLinksGet$Params {
  /**
   * Number of items to skip (for lazy loading)
   */
  offset?: number

  /**
   * Filter by integrity title (case-insensitive)
   */
  search?: string | null

  /**
   * Filter by organization (exact match, OR'd together)
   */
  organization?: Array<string> | null

  /**
   * Filter by owner username (exact match, OR'd together)
   */
  owner?: Array<string> | null

  /**
   * Filter by public access level
   */
  access?: Array<PublicAccess> | null

  /**
   * Filter by recurrence preset
   */
  recurrence?: Array<RecurrencePreset> | null
}

export function listIntegrityLinksIngestionIntegrityLinksGet(
  http: HttpClient,
  rootUrl: string,
  params?: ListIntegrityLinksIngestionIntegrityLinksGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<IntegrityLinkListResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    listIntegrityLinksIngestionIntegrityLinksGet.PATH,
    'get'
  )
  if (params) {
    rb.query('offset', params.offset, {})
    rb.query('search', params.search, {})
    rb.query('organization', params.organization, {})
    rb.query('owner', params.owner, {})
    rb.query('access', params.access, {})
    rb.query('recurrence', params.recurrence, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<IntegrityLinkListResponse>
      })
    )
}

listIntegrityLinksIngestionIntegrityLinksGet.PATH =
  '/ingestion/integrity-links/'
