/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { RecurrencePresetItem } from '../../models/recurrence-preset-item'

export interface ListRecurrencePresetsIngestionRecurrencePresetsGet$Params {}

export function listRecurrencePresetsIngestionRecurrencePresetsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ListRecurrencePresetsIngestionRecurrencePresetsGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<RecurrencePresetItem>>> {
  const rb = new requestBuilders(
    rootUrl,
    listRecurrencePresetsIngestionRecurrencePresetsGet.PATH,
    'get'
  )
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<RecurrencePresetItem>>
      })
    )
}

listRecurrencePresetsIngestionRecurrencePresetsGet.PATH =
  '/ingestion/recurrence-presets'
