/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { JoinableTable } from '../../models/joinable-table'

export interface ListJoinableTablesIngestionIntegrityLinksJoinableTablesGet$Params {}

export function listJoinableTablesIngestionIntegrityLinksJoinableTablesGet(
  http: HttpClient,
  rootUrl: string,
  params?: ListJoinableTablesIngestionIntegrityLinksJoinableTablesGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<JoinableTable>>> {
  const rb = new requestBuilders(
    rootUrl,
    listJoinableTablesIngestionIntegrityLinksJoinableTablesGet.PATH,
    'get'
  )
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<JoinableTable>>
      })
    )
}

listJoinableTablesIngestionIntegrityLinksJoinableTablesGet.PATH =
  '/ingestion/integrity-links/joinable-tables'
