/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { ProcessRequest } from '../../models/process-request'
import { ProcessResponse } from '../../models/process-response'

export interface ProcessStagingDataIngestionProcessPost$Params {
  body: ProcessRequest
}

export function processStagingDataIngestionProcessPost(
  http: HttpClient,
  rootUrl: string,
  params: ProcessStagingDataIngestionProcessPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<ProcessResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    processStagingDataIngestionProcessPost.PATH,
    'post'
  )
  if (params) {
    rb.body(params.body, 'application/json')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ProcessResponse>
      })
    )
}

processStagingDataIngestionProcessPost.PATH = '/ingestion/process/'
