/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { BodySubmitStagingIngestionStagingPost } from '../../models/body-submit-staging-ingestion-staging-post'
import { StagingResponse } from '../../models/staging-response'

export interface SubmitStagingIngestionStagingPost$Params {
  body: BodySubmitStagingIngestionStagingPost
}

export function submitStagingIngestionStagingPost(
  http: HttpClient,
  rootUrl: string,
  params: SubmitStagingIngestionStagingPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<StagingResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    submitStagingIngestionStagingPost.PATH,
    'post'
  )
  if (params) {
    rb.body(params.body, 'multipart/form-data')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<StagingResponse>
      })
    )
}

submitStagingIngestionStagingPost.PATH = '/ingestion/staging/'
