/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { IntegrityLinkResponse } from '../../models/integrity-link-response'

export interface TogglePublishGnIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdPublishGnPut$Params {
  integrity_link_id: string

  /**
   * Set to true to publish, false to unpublish
   */
  publish: boolean
}

export function togglePublishGnIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdPublishGnPut(
  http: HttpClient,
  rootUrl: string,
  params: TogglePublishGnIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdPublishGnPut$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<IntegrityLinkResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    togglePublishGnIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdPublishGnPut.PATH,
    'put'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.query('publish', params.publish, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<IntegrityLinkResponse>
      })
    )
}

togglePublishGnIntegrityLinkIngestionIntegrityLinkIntegrityLinkIdPublishGnPut.PATH =
  '/ingestion/integrity-link/{integrity_link_id}/publish-gn'
