/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { BodyUpdateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch } from '../../models/body-update-schedule-ingestion-integrity-link-integrity-link-id-schedule-patch'
import { IntegrityLinkResponse } from '../../models/integrity-link-response'

export interface UpdateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch$Params {
  integrity_link_id: string
  body?: BodyUpdateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch
}

export function updateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch(
  http: HttpClient,
  rootUrl: string,
  params: UpdateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<IntegrityLinkResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    updateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch.PATH,
    'patch'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.body(params.body, 'application/json')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<IntegrityLinkResponse>
      })
    )
}

updateScheduleIngestionIntegrityLinkIntegrityLinkIdSchedulePatch.PATH =
  '/ingestion/integrity-link/{integrity_link_id}/schedule'
