/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { IntegrityLinkResponse } from '../../models/integrity-link-response'
import { UpdateMetadataGnRequest } from '../../models/update-metadata-gn-request'

export interface UpdateMetadataGnIngestionIntegrityLinkIntegrityLinkIdMetadataGnPut$Params {
  integrity_link_id: string
  body: UpdateMetadataGnRequest
}

export function updateMetadataGnIngestionIntegrityLinkIntegrityLinkIdMetadataGnPut(
  http: HttpClient,
  rootUrl: string,
  params: UpdateMetadataGnIngestionIntegrityLinkIntegrityLinkIdMetadataGnPut$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<IntegrityLinkResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    updateMetadataGnIngestionIntegrityLinkIntegrityLinkIdMetadataGnPut.PATH,
    'put'
  )
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {})
    rb.body(params.body, 'application/json')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<IntegrityLinkResponse>
      })
    )
}

updateMetadataGnIngestionIntegrityLinkIntegrityLinkIdMetadataGnPut.PATH =
  '/ingestion/integrity-link/{integrity_link_id}/metadata-gn'
