/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { requestBuilders } from '../../request-builders';

import { IntegrityLinkRule } from '../../models/integrity-link-rule';
import { UpsertRuleRequest } from '../../models/upsert-rule-request';

export interface UpsertIntegrityLinkRuleIngestionIntegrityLinkIntegrityLinkIdRulesPut$Params {
  integrity_link_id: string;
      body: UpsertRuleRequest
}

export function upsertIntegrityLinkRuleIngestionIntegrityLinkIntegrityLinkIdRulesPut(http: HttpClient, rootUrl: string, params: UpsertIntegrityLinkRuleIngestionIntegrityLinkIntegrityLinkIdRulesPut$Params, context?: HttpContext): Observable<StrictHttpResponse<IntegrityLinkRule>> {
  const rb = new requestBuilders(rootUrl, upsertIntegrityLinkRuleIngestionIntegrityLinkIntegrityLinkIdRulesPut.PATH, 'put');
  if (params) {
    rb.path('integrity_link_id', params.integrity_link_id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IntegrityLinkRule>;
    })
  );
}

upsertIntegrityLinkRuleIngestionIntegrityLinkIntegrityLinkIdRulesPut.PATH = '/ingestion/integrity-link/{integrity_link_id}/rules';
