"""Local (in-process) task executor implementation.

Runs the staging/process logic directly inside the backend process, in a thread
pool, instead of delegating to Airflow. Only the "direct" flows triggered by the
backend API are supported (initial/rerun staging, process from an existing
staging table) — the scheduled re-ingestion pipeline generated by
apps/elt/dags/process-dag-generator.py has no equivalent here and still requires
a real Airflow deployment. There is also no timeout mechanism: get_task_note
always returns None.

Run state lives in memory only and is lost on backend restart.
"""

import os
import tempfile
import threading
import traceback
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import datetime
from typing import Any
from urllib.parse import quote

import requests
from data_manipulation import (
    IntegrityTransformation,
    transform_staging_to_final,
)
from data_manipulation.constants import DB_URI_PREFIX
from data_manipulation.database import create_schema
from data_manipulation.ingestion import (
    ingest_data_from_database_into_postgis,
    ingest_data_from_file_into_postgis,
    ingest_data_from_ftp_into_postgis,
    ingest_data_from_ogc_service_into_postgis,
    ingest_data_from_url_into_postgis,
)
from sqlalchemy import MetaData, Table

from src.core.config import get_staging_schema
from src.core.constants import DEFAULT_DATA_SCHEMA
from src.core.db import data_engine, datafeeder_engine, source_db_key, source_engine
from src.core.encryption import decrypt_basic_auth
from src.core.logging import get_logger
from src.core.task_executor import BaseTaskExecutor, TaskRunInfo, TaskStatus

logger = get_logger()

_STAGING_DAG_ID = "staging_dag"
_PROCESS_DAG_ID = "process_dag"
_MAX_WORKERS = 4

# Container to `docker exec` ogr2ogr into (see docker/compose.datafeeder.yaml, service
# `datafeeder-gdal`, profile `local-executor`) since this executor runs outside of any
# container with GDAL (typically on the host, via `make run-backend-with-local-task-
# executor`). Empty disables the wrapper: ogr2ogr must then already be on PATH.
_GDAL_DOCKER_EXEC_TARGET = os.getenv("DATAFEEDER_GDAL_DOCKER_EXEC_TARGET", "")
_OGR2OGR_WRAPPER_DIR = os.path.join(tempfile.gettempdir(), "datafeeder-gdal-wrapper")


@dataclass
class _RunRecord:
    status: TaskStatus
    logs: str = ""


class LocalTaskExecutor(BaseTaskExecutor):
    """Runs staging/process synchronously in-process instead of via Airflow."""

    def __init__(self) -> None:
        self._install_ogr2ogr_docker_wrapper()
        self._pool = ThreadPoolExecutor(
            max_workers=_MAX_WORKERS, thread_name_prefix="local-task-executor"
        )
        self._registry: dict[tuple[str, str], _RunRecord] = {}
        self._registry_lock = threading.Lock()

    def _install_ogr2ogr_docker_wrapper(self) -> None:
        """Make the `ogr2ogr` calls in data_manipulation.ingestion reach the
        `datafeeder-gdal` sidecar container via `docker exec` instead of a local binary.

        Written under the system temp dir (not /usr/local/bin) so it works without root/
        sudo when this executor runs as a plain host process, then prepended to PATH.
        """
        if not _GDAL_DOCKER_EXEC_TARGET:
            return
        try:
            os.makedirs(_OGR2OGR_WRAPPER_DIR, exist_ok=True)
            wrapper_path = os.path.join(_OGR2OGR_WRAPPER_DIR, "ogr2ogr")
            with open(wrapper_path, "w") as f:
                f.write(f'#!/bin/sh\nexec docker exec "{_GDAL_DOCKER_EXEC_TARGET}" ogr2ogr "$@"\n')
            os.chmod(wrapper_path, 0o755)
            os.environ["PATH"] = _OGR2OGR_WRAPPER_DIR + os.pathsep + os.environ.get("PATH", "")
        except OSError as e:
            logger.warning(f"Failed to install ogr2ogr docker-exec wrapper: {e}")

    def _set_status(self, task_id: str, run_id: str, status: TaskStatus, logs: str = "") -> None:
        with self._registry_lock:
            record = self._registry.get((task_id, run_id))
            if record is None:
                record = _RunRecord(status=status)
                self._registry[(task_id, run_id)] = record
            record.status = status
            if logs:
                record.logs = logs

    def _call_callback(self, url: str | None, callback_type: str, reason: str = "") -> None:
        if not url:
            return
        full_url = f"{url}&reason={quote(reason)}" if callback_type == "failure" else url
        logger.info(f"Calling {callback_type} callback URL: {full_url}")
        try:
            response = requests.post(full_url, timeout=10)
            response.raise_for_status()
        except requests.RequestException as e:
            logger.error(
                f"{callback_type.capitalize()} callback failed | url={full_url} | error={e}"
            )

    # -- staging -----------------------------------------------------------------

    def trigger_staging_task(
        self,
        run_id: str,
        staging_table_name: str,
        source: str,
        source_type: str,
        success_callback_url: str | None = None,
        failure_callback_url: str | None = None,
        encrypted_credentials: str | None = None,
        source_layer: str | None = None,
        source_protocol: str | None = None,
    ) -> TaskRunInfo:
        self._set_status(_STAGING_DAG_ID, run_id, TaskStatus.QUEUED)
        self._pool.submit(
            self._run_staging,
            run_id,
            staging_table_name,
            source,
            source_type,
            success_callback_url,
            failure_callback_url,
            encrypted_credentials,
            source_layer,
            source_protocol,
        )
        return TaskRunInfo(
            task_id=_STAGING_DAG_ID, run_id=run_id, status=TaskStatus.QUEUED, execution_date=None
        )

    def _decrypt_auth(self, encrypted_credentials: str | None) -> tuple[str, str] | None:
        if not encrypted_credentials:
            return None
        with datafeeder_engine.connect() as conn:
            return decrypt_basic_auth(conn, encrypted_credentials)

    def _parse_db_uri(self, source: str) -> tuple[str, str, str]:
        if not source.startswith(DB_URI_PREFIX):
            raise ValueError(
                f"Invalid database source URL format: '{source}'. "
                f"Expected {DB_URI_PREFIX}{{db_key}}/{{schema}}/{{table}}"
            )
        try:
            db_key, schema, table = source.removeprefix(DB_URI_PREFIX).split("/", 2)
        except ValueError:
            raise ValueError(
                f"Invalid database source URL format: '{source}'. "
                f"Expected {DB_URI_PREFIX}{{db_key}}/{{schema}}/{{table}}"
            )
        if not db_key or not schema or not table:
            raise ValueError(
                f"Invalid database source URL: db_key, schema, and table must all be "
                f"non-empty (got '{source}')"
            )
        if db_key != source_db_key or source_engine is None:
            raise ValueError(f"Unknown or unconfigured source database key: '{db_key}'")
        return db_key, schema, table

    def _ingest(
        self,
        source_type: str,
        source: str,
        table_name: str,
        encrypted_credentials: str | None,
        source_layer: str | None,
        source_protocol: str | None,
    ) -> None:
        schema = get_staging_schema()
        match source_type:
            case "FILE":
                ingest_data_from_file_into_postgis(source, table_name, data_engine, schema=schema)
            case "URL":
                auth = self._decrypt_auth(encrypted_credentials)
                ingest_data_from_url_into_postgis(
                    source, table_name, data_engine, schema=schema, auth=auth
                )
            case "FTP":
                auth = self._decrypt_auth(encrypted_credentials)
                ingest_data_from_ftp_into_postgis(source, table_name, data_engine, schema, auth)
            case "DATABASE":
                _, source_schema, source_table = self._parse_db_uri(source)
                engine = source_engine
                assert engine is not None  # validated by _parse_db_uri
                ingest_data_from_database_into_postgis(
                    source_schema=source_schema,
                    source_table=source_table,
                    source_engine=engine,
                    target_table=table_name,
                    target_engine=data_engine,
                    target_schema=schema,
                )
            case "API":
                ingest_data_from_ogc_service_into_postgis(
                    source,
                    source_layer or "",
                    source_protocol or "wfs",
                    table_name,
                    data_engine,
                    schema=schema,
                )
            case _:
                raise ValueError(f"Unsupported source_type: {source_type}")

    def _run_staging(
        self,
        run_id: str,
        staging_table_name: str,
        source: str,
        source_type: str,
        success_callback_url: str | None,
        failure_callback_url: str | None,
        encrypted_credentials: str | None,
        source_layer: str | None,
        source_protocol: str | None,
    ) -> None:
        self._set_status(_STAGING_DAG_ID, run_id, TaskStatus.RUNNING)
        try:
            self._ingest(
                source_type,
                source,
                staging_table_name,
                encrypted_credentials,
                source_layer,
                source_protocol,
            )
            self._set_status(_STAGING_DAG_ID, run_id, TaskStatus.SUCCESS)
            self._call_callback(success_callback_url, "success")
        except Exception as e:
            logger.exception(f"Local staging run {run_id} failed")
            logs = f"{e}\n\n{traceback.format_exc()}"
            self._set_status(_STAGING_DAG_ID, run_id, TaskStatus.FAILED, logs=logs)
            self._call_callback(failure_callback_url, "failure")

    # -- process -------------------------------------------------------------

    def trigger_process_task(
        self,
        run_id: str,
        staging_table_name: str | None = None,
        final_table_name: str = "",
        integrity_transformation: dict[str, Any] | None = None,
        success_callback_url: str | None = None,
        failure_callback_url: str | None = None,
        last_retrieval_timestamp: datetime | None = None,
        target_schema: str = DEFAULT_DATA_SCHEMA,
    ) -> TaskRunInfo:
        self._set_status(_PROCESS_DAG_ID, run_id, TaskStatus.QUEUED)
        self._pool.submit(
            self._run_process,
            run_id,
            staging_table_name,
            final_table_name,
            integrity_transformation or {},
            success_callback_url,
            failure_callback_url,
            last_retrieval_timestamp,
            target_schema,
        )
        return TaskRunInfo(
            task_id=_PROCESS_DAG_ID, run_id=run_id, status=TaskStatus.QUEUED, execution_date=None
        )

    def _transform(
        self,
        staging_table_name: str,
        final_table_name: str,
        integrity_transformation: dict[str, Any],
        last_retrieval_timestamp: datetime | None,
        target_schema: str,
    ) -> None:
        staging_schema = get_staging_schema()
        transformation_config = IntegrityTransformation(**integrity_transformation)

        if last_retrieval_timestamp:
            try:
                logger.info(
                    f"Re-run detected. Dropping existing final table: "
                    f"{target_schema}.{final_table_name}"
                )
                with data_engine.connect() as conn:
                    metadata = MetaData(schema=target_schema)
                    table = Table(final_table_name, metadata)
                    table.drop(conn, checkfirst=True)
                    conn.commit()
            except Exception as drop_error:
                logger.warning(f"Failed to drop existing final table: {drop_error}")

        create_schema(data_engine, target_schema)

        # Transformation runs entirely in PostGIS (CREATE TABLE AS) — no data is
        # loaded into Python memory. Mirrors apps/elt/dags/task_groups/transformation.py
        # so the direct (LOCAL executor) and Airflow flows apply identical logic.
        row_count = transform_staging_to_final(
            staging_table=staging_table_name,
            final_table=final_table_name,
            engine=data_engine,
            config=transformation_config,
            staging_schema=staging_schema,
            final_schema=target_schema,
            create_id=True,
        )

        if row_count == 0:
            raise ValueError("No data to write after transformation.")

        logger.info(f"Successfully wrote {row_count} rows to final table")

        logger.info(f"Dropping staging table {staging_schema}.{staging_table_name}")
        metadata = MetaData(schema=staging_schema)
        t = Table(staging_table_name, metadata)
        t.drop(data_engine, checkfirst=True)

    def _run_process(
        self,
        run_id: str,
        staging_table_name: str | None,
        final_table_name: str,
        integrity_transformation: dict[str, Any],
        success_callback_url: str | None,
        failure_callback_url: str | None,
        last_retrieval_timestamp: datetime | None,
        target_schema: str,
    ) -> None:
        self._set_status(_PROCESS_DAG_ID, run_id, TaskStatus.RUNNING)
        try:
            if not staging_table_name:
                raise ValueError("staging_table_name is required")
            self._transform(
                staging_table_name,
                final_table_name,
                integrity_transformation,
                last_retrieval_timestamp,
                target_schema,
            )
            self._set_status(_PROCESS_DAG_ID, run_id, TaskStatus.SUCCESS)
            self._call_callback(success_callback_url, "success")
        except Exception as e:
            logger.exception(f"Local process run {run_id} failed")
            logs = f"{e}\n\n{traceback.format_exc()}"
            self._set_status(_PROCESS_DAG_ID, run_id, TaskStatus.FAILED, logs=logs)
            self._call_callback(failure_callback_url, "failure")

    # -- status/logs/note -----------------------------------------------------

    def get_task_status(self, task_id: str, run_id: str) -> TaskRunInfo:
        with self._registry_lock:
            record = self._registry.get((task_id, run_id))
        if record is None:
            raise ValueError(f"Unknown local task run: {task_id}/{run_id}")
        return TaskRunInfo(
            task_id=task_id, run_id=run_id, status=record.status, execution_date=None
        )

    def get_task_logs(self, task_id: str, run_id: str) -> str:
        with self._registry_lock:
            record = self._registry.get((task_id, run_id))
        return record.logs if record else ""

    def get_task_note(self, task_id: str, run_id: str) -> str | None:
        del task_id, run_id  # unused: no timeout mechanism to report a note for
        return None
