/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { GroupItem } from '../../models/group-item'

export interface ListGroupsMetadataGroupsGet$Params {}

export function listGroupsMetadataGroupsGet(
  http: HttpClient,
  rootUrl: string,
  params?: ListGroupsMetadataGroupsGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<Array<GroupItem>>> {
  const rb = new requestBuilders(
    rootUrl,
    listGroupsMetadataGroupsGet.PATH,
    'get'
  )
  if (params) {
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<Array<GroupItem>>
      })
    )
}

listGroupsMetadataGroupsGet.PATH = '/metadata/groups/'
