"""Tests for the dag_run_id conventions module."""

from src.core.run_ids import (
    extract_integrity_link_id,
    is_manual_process_run,
    make_initial_staging_run_id,
    make_manual_process_run_id,
    make_staging_rerun_id,
    process_run_like,
    process_run_prefix,
    staging_run_like,
    staging_run_prefix,
)

LINK_ID = "00000000-0000-0000-0000-000000000001"


class TestMakers:
    def test_initial_staging_run_id_is_the_link_id(self) -> None:
        assert make_initial_staging_run_id(LINK_ID) == LINK_ID

    def test_staging_rerun_id(self) -> None:
        assert make_staging_rerun_id(LINK_ID, 1700000000) == f"{LINK_ID}_1700000000"

    def test_manual_process_run_id(self) -> None:
        assert make_manual_process_run_id(LINK_ID, 1700000000) == f"{LINK_ID}_1700000000_manual"


class TestMatchers:
    def test_extract_integrity_link_id(self) -> None:
        assert extract_integrity_link_id(f"{LINK_ID}_1700000000_manual") == LINK_ID
        assert extract_integrity_link_id(LINK_ID) == LINK_ID

    def test_is_manual_process_run(self) -> None:
        assert is_manual_process_run(make_manual_process_run_id(LINK_ID, 1))
        assert not is_manual_process_run(f"{LINK_ID}_20260601T000000")

    def test_prefixes_match_all_generated_run_ids(self) -> None:
        assert make_initial_staging_run_id(LINK_ID).startswith(staging_run_prefix(LINK_ID))
        assert make_staging_rerun_id(LINK_ID, 1).startswith(staging_run_prefix(LINK_ID))
        assert make_manual_process_run_id(LINK_ID, 1).startswith(process_run_prefix(LINK_ID))
        # scheduled process run id, generated by apps/elt/dags/process-dag-generator.py
        assert f"{LINK_ID}_20260601T000000".startswith(process_run_prefix(LINK_ID))

    def test_like_patterns(self) -> None:
        assert staging_run_like(LINK_ID) == f"{LINK_ID}%"
        assert process_run_like(LINK_ID) == f"{LINK_ID}_%"
