/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { GeneratedMetadata } from '../../models/generated-metadata'

export interface GenerateMetadataForIntegrityLinkLlmGenerateMetadataIntlinkIdGet$Params {
  intlink_id: string
}

export function generateMetadataForIntegrityLinkLlmGenerateMetadataIntlinkIdGet(
  http: HttpClient,
  rootUrl: string,
  params: GenerateMetadataForIntegrityLinkLlmGenerateMetadataIntlinkIdGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<GeneratedMetadata>> {
  const rb = new requestBuilders(
    rootUrl,
    generateMetadataForIntegrityLinkLlmGenerateMetadataIntlinkIdGet.PATH,
    'get'
  )
  if (params) {
    rb.path('intlink_id', params.intlink_id, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<GeneratedMetadata>
      })
    )
}

generateMetadataForIntegrityLinkLlmGenerateMetadataIntlinkIdGet.PATH =
  '/llm/generate_metadata/{intlink_id}'
