/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { requestBuilders } from '../../request-builders';


export interface HealthCheckUtilsHealthCheckGet$Params {
}

export function healthCheckUtilsHealthCheckGet(http: HttpClient, rootUrl: string, params?: HealthCheckUtilsHealthCheckGet$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new requestBuilders(rootUrl, healthCheckUtilsHealthCheckGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

healthCheckUtilsHealthCheckGet.PATH = '/utils/health-check/';
