
services:
  datafeeder-frontend:
    profiles:
      - datafeeder
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
#    environment:
#        - OVERRIDE_BASE_HREF=ds
    ports:
      - "8001:8080"

  datafeeder-backend:
    profiles:
      - datafeeder
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile
      target: development
    ports:
      - "8002:8000"
    volumes:
      - ./datadir:/etc/georchestra
      # for dev only
      - ../apps:/app/apps
      - ../pyproject.toml:/app/pyproject.toml
      - ../uv.lock:/app/uv.lock
      - /tmp/:/tmp:rw
    environment:
      - DATADIR=/etc/georchestra
    env_file:
      - .envs-common
      - .envs-ldap
      - .envs-hosts
      - .envs-database-georchestra
    restart: always

  datadb:
    image: postgis/postgis
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: postgres # default database
    volumes:
      - pg_data:/var/lib/postgresql/
      - ./data-db-init.sql:/docker-entrypoint-initdb.d/data-db-init.sql

volumes:
  pg_data: