
services:
  datakern-frontend:
    profiles:
      - datakern
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    ports:
      - "8001:8080"

  datakern-backend:
    profiles:
      - datakern
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile
      target: development
    ports:
      - "8002:8000"
    volumes:
      - ./datadir:/etc/georchestra
      # for dev only
      - ../apps:/app/apps
      - ../pyproject.toml:/app/pyproject.toml
      - ../uv.lock:/app/uv.lock
    env_file:
      - .envs-common
      - .envs-ldap
      - .envs-hosts
      - .envs-database-georchestra
    restart: always
