
services:
  datakern-frontend:
    profiles:
      - datakern
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    ports:
      - "8001:8080"

  datakern-backend:
    profiles:
      - datakern
    build:
      context: ../
      dockerfile: ./apps/backend/Dockerfile
      target: development
    ports:
      - "8002:8000"