project_name="Datakern"
api_v1_str="/api/v1"
environment="local" ;"local", "staging", "production"
sentry_dsn=""
airflow_username="airflow"
airflow_password="airflow"
api_username="testadmin"
api_password="testadmin"
geoserver_password="testadmin"
access_token_expire_minutes=60
backend_cors_origins=[]
email_reset_token_expire_hours=48
