/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { ImportRequest } from '../../models/import-request'
import { ImportResponse } from '../../models/import-response'

export interface CreateImportImportPost$Params {
  body: ImportRequest
}

export function createImportImportPost(
  http: HttpClient,
  rootUrl: string,
  params: CreateImportImportPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<ImportResponse>> {
  const rb = new requestBuilders(rootUrl, createImportImportPost.PATH, 'post')
  if (params) {
    rb.body(params.body, 'application/json')
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<ImportResponse>
      })
    )
}

createImportImportPost.PATH = '/import/'
