/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

import { StatusResponse } from '../../models/status-response'

export interface GetImportStatusV1ImportStatusGet$Params {
  dag_id: string
  dag_run_id: string
}

export function getImportStatusV1ImportStatusGet(
  http: HttpClient,
  rootUrl: string,
  params: GetImportStatusV1ImportStatusGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<StatusResponse>> {
  const rb = new requestBuilders(
    rootUrl,
    getImportStatusV1ImportStatusGet.PATH,
    'get'
  )
  if (params) {
    rb.query('dag_id', params.dag_id, {})
    rb.query('dag_run_id', params.dag_run_id, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<StatusResponse>
      })
    )
}

getImportStatusV1ImportStatusGet.PATH = '/v1/import/status'
