/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface FinalSuccessCallbackCallbacksFinalSuccessPost$Params {
  /**
   * DAG run ID
   */
  dag_run_id: string

  /**
   * Name of the final table
   */
  final_table_name: string
}

export function finalSuccessCallbackCallbacksFinalSuccessPost(
  http: HttpClient,
  rootUrl: string,
  params: FinalSuccessCallbackCallbacksFinalSuccessPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(
    rootUrl,
    finalSuccessCallbackCallbacksFinalSuccessPost.PATH,
    'post'
  )
  if (params) {
    rb.query('dag_run_id', params.dag_run_id, {})
    rb.query('final_table_name', params.final_table_name, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<any>
      })
    )
}

finalSuccessCallbackCallbacksFinalSuccessPost.PATH = '/callbacks/final/success'
