/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface StagingSuccessCallbackCallbacksStagingSuccessPost$Params {
  /**
   * DAG run ID
   */
  dag_run_id: string

  /**
   * Name of the staging table
   */
  staging_table_name: string

  /**
   * Owner of the staging table
   */
  owner: string

  /**
   * Organization of the staging table
   */
  organization: string
}

export function stagingSuccessCallbackCallbacksStagingSuccessPost(
  http: HttpClient,
  rootUrl: string,
  params: StagingSuccessCallbackCallbacksStagingSuccessPost$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(
    rootUrl,
    stagingSuccessCallbackCallbacksStagingSuccessPost.PATH,
    'post'
  )
  if (params) {
    rb.query('dag_run_id', params.dag_run_id, {})
    rb.query('staging_table_name', params.staging_table_name, {})
    rb.query('owner', params.owner, {})
    rb.query('organization', params.organization, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<any>
      })
    )
}

stagingSuccessCallbackCallbacksStagingSuccessPost.PATH =
  '/callbacks/staging/success'
