/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { requestBuilders } from '../../request-builders';


export interface ProxyGeonetworkGeonetworkPathGet_5$Params {
  path: string;
}

export function proxyGeonetworkGeonetworkPathGet_5(http: HttpClient, rootUrl: string, params: ProxyGeonetworkGeonetworkPathGet_5$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(rootUrl, proxyGeonetworkGeonetworkPathGet_5.PATH, 'patch');
  if (params) {
    rb.path('path', params.path, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

proxyGeonetworkGeonetworkPathGet_5.PATH = '/geonetwork/{path}';
