/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface ProxyGeonetworkGeonetworkPathPut_3$Params {
  path: string
}

export function proxyGeonetworkGeonetworkPathPut_3(
  http: HttpClient,
  rootUrl: string,
  params: ProxyGeonetworkGeonetworkPathPut_3$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<any>> {
  const rb = new requestBuilders(
    rootUrl,
    proxyGeonetworkGeonetworkPathPut_3.PATH,
    'delete'
  )
  if (params) {
    rb.path('path', params.path, {})
  }

  return http
    .request(
      rb.build({ responseType: 'json', accept: 'application/json', context })
    )
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<any>
      })
    )
}

proxyGeonetworkGeonetworkPathPut_3.PATH = '/geonetwork/{path}'
