/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Description of a single dataset attribute/column.
 *
 * Note: string max_length limits are intentionally added to help control LLM token usage.
 */
export interface AttributeInfo {
  /**
   * Human-readable description of the column in French
   */
  description: string

  /**
   * Column name
   */
  name: string

  /**
   * ISO 19110 type (e.g. integer, string (50), GM_Point)
   */
  type: string
}
