/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from '../models/import-type'
export interface BodySubmitStagingIngestionStagingPost {
  auth_enabled?: boolean
  file?: Blob | null
  password?: string | null
  type: ImportType
  url?: string | null
  username?: string | null
}
