/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from '../models/import-type'
export interface BodySubmitStagingIngestionStagingPost {
  auth_enabled?: boolean
  db_schema?: string | null
  db_table?: string | null
  file?: string | null
  ftp_host?: string | null
  ftp_path?: string | null
  ftp_port?: number | null
  generate_metadata_with_ai?: boolean
  layer_name?: string | null
  password?: string | null
  service_protocol?: string | null
  service_url?: string | null
  type: ImportType
  url?: string | null
  username?: string | null
}
