/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from '../models/import-type'
export interface BodyEditStagingIngestionStagingIntegrityLinkIdPut {
  auth_enabled?: boolean
  db_schema?: string | null
  db_table?: string | null
  file?: Blob | null
  ftp_host?: string | null
  ftp_path?: string | null
  ftp_port?: number | null
  password?: string | null
  type: ImportType
  url?: string | null
  username?: string | null
}
