/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from '../models/import-type'
export interface BodySubmitStagingIngestionStagingPost {
  file?: Blob | null
  type: ImportType
  url?: string | null
}
