/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeoServerLayer } from '../models/geo-server-layer'
import { IntegrityLink } from '../models/integrity-link'
export interface BroadcastResponse {
  geoserver_layer?: GeoServerLayer | null
  geoserver_workspace: {
    [key: string]: string
  }
  integrity_link: IntegrityLink
}
