/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CastType } from './cast-type';

/**
 * Each possible value of `CastType`
 */
export const CAST_TYPE: CastType[] = [
  'boolean',
  'numeric',
  'text',
  'date'
];