/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunResponse } from '../models/dag-run-response';

/**
 * DAG Run Collection serializer for responses.
 */
export interface DagRunCollectionResponse {
  dag_runs: Array<DagRunResponse>;
  total_entries: number;
}
