/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Class with TriggeredBy types for DagRun.
 */
export type DagRunTriggeredByType =
  | 'cli'
  | 'operator'
  | 'rest_api'
  | 'ui'
  | 'test'
  | 'timetable'
  | 'asset'
  | 'backfill'
