/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunState } from '../models/dag-run-state'
import { DagRunTriggeredByType } from '../models/dag-run-triggered-by-type'
import { DagRunType } from '../models/dag-run-type'
import { DagVersionResponse } from '../models/dag-version-response'

/**
 * DAG Run serializer for responses.
 */
export interface DagRunResponse {
  bundle_version?: string | null
  conf?: {
    [key: string]: any
  } | null
  dag_display_name: string
  dag_id: string
  dag_run_id: string
  dag_versions: Array<DagVersionResponse>
  data_interval_end?: string | null
  data_interval_start?: string | null
  duration?: number | number | null
  end_date?: string | null
  last_scheduling_decision?: string | null
  logical_date?: string | null
  note?: string | null
  partition_key?: string | null
  queued_at?: string | null
  run_after: string
  run_type: DagRunType
  start_date?: string | null
  state: DagRunState
  triggered_by?: DagRunTriggeredByType | null
  triggering_user_name?: string | null
}
