/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunResponse } from '../models/dag-run-response'

/**
 * Dag Run collection response supporting both offset and cursor pagination.  A single flat model is used instead of a discriminated union (``Annotated[Offset | Cursor, Field(discriminator=...)]``) because the OpenAPI ``oneOf`` + ``discriminator`` construct is not handled correctly by ``@hey-api/openapi-ts`` / ``@7nohe/openapi-react-query-codegen``: return types degrade to ``unknown`` in JSDoc and can produce incorrect TypeScript types (see hey-api/openapi-ts#1613, #3270).
 */
export interface DagRunCollectionResponse {
  dag_runs: Array<DagRunResponse>
  next_cursor?: string | null
  previous_cursor?: string | null
  total_entries?: number | null
  total_entries_limit?: number | null
}
