/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunState } from '../models/dag-run-state'

/**
 * Response model for DAG run status endpoint with optional failure reason
 */
export interface DagRunStatusResponse {
  reason?: string | null
  status: DagRunState
}
