/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * All possible states that a DagRun can be in.  These are "shared" with TaskInstanceState in some parts of the code, so please ensure that their values always match the ones with the same name in TaskInstanceState.
 */
export type DagRunState = 'queued' | 'running' | 'success' | 'failed';

