/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunState } from './dag-run-state';

/**
 * Each possible value of `DagRunState`
 */
export const DAG_RUN_STATE: DagRunState[] = [
  'queued',
  'running',
  'success',
  'failed'
];