/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Dag Version serializer for responses.
 */
export interface DagVersionResponse {
  bundle_name?: (string | null);
  bundle_url?: (string | null);
  bundle_version?: (string | null);
  created_at: string;
  dag_display_name: string;
  dag_id: string;
  id: string;
  version_number: number;
}
