/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunTriggeredByType } from './dag-run-triggered-by-type'

/**
 * Each possible value of `DagRunTriggeredByType`
 */
export const DAG_RUN_TRIGGERED_BY_TYPE: DagRunTriggeredByType[] = [
  'cli',
  'operator',
  'rest_api',
  'ui',
  'test',
  'timetable',
  'asset',
  'backfill'
]
