/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DagRunType } from './dag-run-type'

/**
 * Each possible value of `DagRunType`
 */
export const DAG_RUN_TYPE: DagRunType[] = [
  'backfill',
  'scheduled',
  'manual',
  'asset_triggered'
]
