/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EventLogResponse } from '../models/event-log-response'

/**
 * Event Log Collection Response.
 */
export interface EventLogCollectionResponse {
  event_logs: Array<EventLogResponse>
  total_entries: number
}
