/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Event Log Response.
 */
export interface EventLogResponse {
  dag_display_name?: string | null
  dag_id?: string | null
  event: string
  event_log_id: number
  extra?: string | null
  logical_date?: string | null
  map_index?: number | null
  owner?: string | null
  run_id?: string | null
  task_display_name?: string | null
  task_id?: string | null
  try_number?: number | null
  when: string
}
