/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FeatureAnnotatedUnionPointMultiPointLineStringMultiLineStringPolygonMultiPolygonGeometryCollectionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorTypeDictStrAny } from '../models/feature-annotated-union-point-multi-point-line-string-multi-line-string-polygon-multi-polygon-geometry-collection-field-info-annotation-none-type-required-true-discriminator-type-dict-str-any'
export interface FeatureCollectionFeatureAnnotatedUnionPointMultiPointLineStringMultiLineStringPolygonMultiPolygonGeometryCollectionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorTypeDictStrAny {
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number]
    | null
  features: Array<FeatureAnnotatedUnionPointMultiPointLineStringMultiLineStringPolygonMultiPolygonGeometryCollectionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorTypeDictStrAny>
  type: 'FeatureCollection'
}
