/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeometryCollection } from '../models/geometry-collection'
import { LineString } from '../models/line-string'
import { MultiLineString } from '../models/multi-line-string'
import { MultiPoint } from '../models/multi-point'
import { MultiPolygon } from '../models/multi-polygon'
import { Point } from '../models/point'
import { Polygon } from '../models/polygon'
export interface FeatureAnnotatedUnionPointMultiPointLineStringMultiLineStringPolygonMultiPolygonGeometryCollectionFieldInfoAnnotationNoneTypeRequiredTrueDiscriminatorTypeDictStrAny {
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number]
    | null
  geometry:
    | (
        | Point
        | MultiPoint
        | LineString
        | MultiLineString
        | Polygon
        | MultiPolygon
        | GeometryCollection
      )
    | null
  id?: number | string | null
  properties: {
    [key: string]: any
  } | null
  type: 'Feature'
}
