/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileType } from './file-type'

/**
 * Each possible value of `FileType`
 */
export const FILE_TYPE: FileType[] = ['csv', 'geojson', 'shapefile', 'gpkg']
