/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Filter comparison operator for column filtering.
 */
export type FilterOperator = 'exactly' | 'contains' | 'starts_with';

