/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FilterOperator } from './filter-operator';

/**
 * Each possible value of `FilterOperator`
 */
export const FILTER_OPERATOR: FilterOperator[] = [
  'exactly',
  'contains',
  'starts_with'
];