/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Force projection configuration for coordinate columns
 */
export interface ForceProjection {
  type?: string;
  x_column?: (string | null);
  y_column?: (string | null);
}
