/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LlmMetadataDataSource } from '../models/llm-metadata-data-source'
import { LlmMetadataMode } from '../models/llm-metadata-mode'

/**
 * Request body for AI metadata generation.
 */
export interface GenerateMetadataRequest {
  current_values?: {
    [key: string]: any
  } | null
  data_source?: LlmMetadataDataSource
  extra_context?: string | null
  mode?: LlmMetadataMode
}
