/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttributeInfo } from '../models/attribute-info'
import { TemporalExtent } from '../models/temporal-extent'

/**
 * Structured metadata generated by the LLM.
 */
export interface GeneratedMetadata {
  /**
   * A clear description of the dataset contents and purpose
   */
  abstract: string

  /**
   * Description of each attribute/column of the dataset
   */
  attribute_descriptions: Array<AttributeInfo>

  /**
   * Relevant thematic keywords for the dataset
   */
  keywords: Array<string>

  /**
   * Temporal extent of the dataset inferred from column names, sample data, or table name. Set to null if no temporal information can be found.
   */
  temporal_extent?: TemporalExtent | null

  /**
   * A concise, human-readable title for the dataset
   */
  title: string

  /**
   * One or more ISO 19115 topic category codes that best describe the dataset (e.g. ['transportation', 'planningCadastre'])
   */
  topic_categories: Array<string>
}
