/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Request body for AI metadata generation.
 */
export interface GenerateMetadataRequest {
  current_values?: {
    [key: string]: any
  } | null
  data_source?: 'staging' | 'final'
  extra_context?: string | null
  mode?: 'regenerate' | 'rewrite'
}
