/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WfsUrls } from '../models/wfs-urls'
import { WmsUrls } from '../models/wms-urls'
export interface GeoServerLayer {
  datastore: string
  layer: string
  layer_qualified_name: string
  table: string
  wfs?: WfsUrls | null
  wms?: WmsUrls | null
  workspace: string
}
