/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LineString } from '../models/line-string';
import { MultiLineString } from '../models/multi-line-string';
import { MultiPoint } from '../models/multi-point';
import { MultiPolygon } from '../models/multi-polygon';
import { Point } from '../models/point';
import { Polygon } from '../models/polygon';

/**
 * GeometryCollection Model
 */
export interface GeometryCollection {
  bbox?: ([number, number, number, number] | [number, number, number, number, number, number] | null);
  geometries: Array<(Point | MultiPoint | LineString | MultiLineString | Polygon | MultiPolygon | GeometryCollection)>;
  type: 'GeometryCollection';
}
