/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportTaskStatus } from './import-task-status'

/**
 * Each possible value of `ImportTaskStatus`
 */
export const IMPORT_TASK_STATUS: ImportTaskStatus[] = [
  'queued',
  'running',
  'success',
  'failed',
  'not_found'
]
