/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from './import-type';

/**
 * Each possible value of `ImportType`
 */
export const IMPORT_TYPE: ImportType[] = [
  'url',
  'file',
  'database',
  'api',
  'ftp'
];