/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Response model for import endpoint
 */
export interface ImportResponse {
  dag_id: string
  dag_run_id: string
  status: string
}
