/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Possible task statuses
 */
export type ImportTaskStatus =
  | 'queued'
  | 'running'
  | 'success'
  | 'failed'
  | 'not_found'
