/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { IntegrityLinkListItem } from '../models/integrity-link-list-item'

/**
 * Response for integrity links list with lazy loading support.
 */
export interface IntegrityLinkListResponse {
  has_more: boolean
  items: Array<IntegrityLinkListItem>
  next_offset: number
  offset: number
}
