/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IntegrityLink {
  created_at?: string | null
  data_id?: string | null
  final_table_name?: string | null
  id?: string | null
  integrity_organization: string
  integrity_owner: string
  integrity_title?: string | null
  integrity_transformation?: {
    [key: string]: any
  } | null
  last_retrieval_timestamp?: string | null
  metadata_id?: string | null
  schedule?: string | null
  schedule_enabled?: boolean
  staging_retrieve_time?: string | null
  staging_table_name?: string
}
