/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileType } from '../models/file-type'
import { ImportType } from '../models/import-type'

/**
 * Response model for integrity link in list view (excludes sensitive fields).
 */
export interface IntegrityLinkListItem {
  /**
   * User's effective access level: ADMIN, OWNER, WRITE, or READ
   */
  access_level?: string | null
  created_at: string | null
  data_id: string | null
  final_table_name: string | null
  has_final_table?: boolean
  id: string
  integrity_organization: string
  integrity_owner: string
  integrity_title: string | null
  last_retrieval_timestamp: string | null
  metadata_id: string | null
  schedule: string | null
  schedule_enabled: boolean
  source_file_name: string | null
  source_file_type: FileType | null
  source_import_type: ImportType
  source_layer?: string | null
  source_protocol?: string | null
  source_url: string | null
  staging_table_name: string
}
