/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileType } from '../models/file-type'
import { ImportType } from '../models/import-type'

/**
 * Response model for IntegrityLink entity.
 */
export interface IntegrityLinkResponse {
  access_level?: string | null
  created_at: string | null
  data_id: string | null
  final_table_name: string | null
  gn_is_published: boolean | null
  id: string
  integrity_organization: string
  integrity_owner: string
  integrity_title: string | null
  integrity_transformation?: {
    [key: string]: any
  } | null
  last_retrieval_timestamp: string | null
  metadata_id: string | null
  schedule: string | null
  schedule_enabled: boolean
  source_file_name: string | null
  source_file_type: FileType | null
  source_import_type: ImportType
  source_url: string | null
  source_username: string | null
  staging_retrieve_time: string | null
  staging_table_name: string
}
