/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * LEFT JOIN of the staging table with another table of the same (data) database.
 */
export interface JoinConfig {
  /**
   * Columns of the joined table to add to the output. Empty = no join.
   */
  columns?: Array<string>

  /**
   * Join key column of the staging table
   */
  source_column: string

  /**
   * Name of the table to join
   */
  table_name: string

  /**
   * Schema of the table to join, e.g. an org schema
   */
  table_schema: string

  /**
   * Join key column of the joined table
   */
  target_column: string
}
