/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * A table available as a join target.
 */
export interface JoinableTable {
  id: string
  integrity_title: string | null
  table_name: string
  table_schema: string
}
