/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LlmMetadataDataSource } from './llm-metadata-data-source'

/**
 * Each possible value of `LlmMetadataDataSource`
 */
export const LLM_METADATA_DATA_SOURCE: LlmMetadataDataSource[] = [
  'staging',
  'final'
]
