/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LlmMetadataMode } from './llm-metadata-mode'

/**
 * Each possible value of `LlmMetadataMode`
 */
export const LLM_METADATA_MODE: LlmMetadataMode[] = ['regenerate', 'rewrite']
