/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Position2D } from '../models/position-2-d'
import { Position3D } from '../models/position-3-d'

/**
 * MultiPoint Model
 */
export interface MultiPoint {
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number]
    | null
  coordinates: Array<Position2D | Position3D>
  type: 'MultiPoint'
}
