/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Position2D } from '../models/position-2-d'
import { Position3D } from '../models/position-3-d'

/**
 * Point Model
 */
export interface Point {
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number]
    | null
  coordinates: Position2D | Position3D
  type: 'Point'
}
