/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Position2D } from '../models/position-2-d'
import { Position3D } from '../models/position-3-d'

/**
 * Polygon Model
 */
export interface Polygon {
  bbox?:
    | [number, number, number, number]
    | [number, number, number, number, number, number]
    | null
  coordinates: Array<Array<Position2D | Position3D>>
  type: 'Polygon'
}
