/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecurrencePreset } from '../models/recurrence-preset'

/**
 * Request model for final import endpoint
 */
export interface ProcessRequest {
  generate_metadata_with_ai?: boolean
  integrity_link_id: string
  recurrence?: RecurrencePreset | null
  title?: string | null
}
