/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request model for final import endpoint
 */
export interface ProcessRequest {
  integrity_link_id: string;
  title: string;
}
