/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicAccess } from './public-access'

/**
 * Each possible value of `PublicAccess`
 */
export const PUBLIC_ACCESS: PublicAccess[] = [
  'unconfigured',
  'restricted',
  'open'
]
