/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Public access level of a dataset, shown on the dashboard.
 */
export type PublicAccess = 'unconfigured' | 'restricted' | 'open'
