/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Public (unauthenticated) access level of a dataset, shown on the dashboard.
 *
 * Distinct from EffectiveAccess in src/core/security.py (the *caller's*
 * access level). Lives here rather than in security.py to avoid a circular
 * import: security.py already imports from models/integrity_link.py, which
 * imports ImportType from this module.
 */
export type PublicAccess = 'unconfigured' | 'restricted' | 'open'
