/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecurrencePreset } from '../models/recurrence-preset'
export interface RecurrencePresetItem {
  cron: string
  id: RecurrencePreset
}
