/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type RecurrencePreset =
  | 'EVERY_MINUTE'
  | 'EVERY_HOUR'
  | 'EVERY_DAY'
  | 'EVERY_WEEK'
  | 'EVERY_MONTH'
  | 'EVERY_YEAR'
