/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RecurrencePreset } from './recurrence-preset'

/**
 * Each possible value of `RecurrencePreset`
 */
export const RECURRENCE_PRESET: RecurrencePreset[] = [
  'EVERY_MINUTE',
  'EVERY_HOUR',
  'EVERY_DAY',
  'EVERY_WEEK',
  'EVERY_MONTH',
  'EVERY_YEAR'
]
