/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleValue } from './rule-value';

/**
 * Each possible value of `RuleValue`
 */
export const RULE_VALUE: RuleValue[] = [
  'READ',
  'WRITE'
];