/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleType } from './rule-type'

/**
 * Each possible value of `RuleType`
 */
export const RULE_TYPE: RuleType[] = ['DATA', 'METADATA']
