/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectionSetting } from '../models/projection-setting';

/**
 * Response model for settings endpoint.
 *
 * Returns application settings including available projections.
 */
export interface SettingsResponse {
  projections: Array<ProjectionSetting>;
}
