/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskStatus } from '../models/task-status'

/**
 * Response model for import endpoint
 */
export interface StagingResponse {
  dag_id: string
  dag_run_id: string
  integrity_link_id: string
  status: TaskStatus
}
