/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColumnMetadata } from '../models/column-metadata'
import { FileType } from '../models/file-type'
import { ForceProjection } from '../models/force-projection'
import { ImportType } from '../models/import-type'

/**
 * Metadata for staging data
 */
export interface StagingMetadataResponse {
  columns: Array<ColumnMetadata>
  file_type: FileType | null
  force_projection?: ForceProjection | null
  import_type: ImportType
  original_projection?: string | null
  row_count: number
  title: string
}
