/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Preview data from staging table
 */
export interface StagingPreviewResponse {
  data: Array<{
    [key: string]: any
  }>
}
