/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportType } from '../models/import-type'

/**
 * Request model for import endpoint
 */
export interface StagingRequest {
  type: ImportType
  url: string
}
