/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColumnMetadata } from '../models/column-metadata'
import { FileType } from '../models/file-type'
import { ForceProjection } from '../models/force-projection'

/**
 * Metadata for staging data
 */
export interface StagingMetadata {
  columns: Array<ColumnMetadata>
  file_type: FileType | null
  force_projection?: ForceProjection | null
  title: string
}
