/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ColumnConfigInput } from '../models/column-config-input';
import { FileType } from '../models/file-type';
import { ForceProjection } from '../models/force-projection';

/**
 * Metadata for staging data
 */
export interface StagingMetadata {
  columns: Array<ColumnConfigInput>;
  file_type: (FileType | null);
  force_projection?: (ForceProjection | null);
  original_projection?: (string | null);
  title: string;
}
