/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImportTaskStatus } from '../models/import-task-status'

/**
 * Response model for status endpoint
 */
export interface StatusResponse {
  status: ImportTaskStatus
}
