/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Response model for status endpoint
 */
export interface StatusResponse {
  dag_id: string
  dag_run_id: string
  error?: string | null
  status: string
}
