/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskStatus } from './task-status'

/**
 * Each possible value of `TaskStatus`
 */
export const TASK_STATUS: TaskStatus[] = [
  'queued',
  'running',
  'success',
  'failed',
  'up_for_retry',
  'up_for_reschedule',
  'upstream_failed',
  'skipped',
  'deferred',
  'removed',
  'restarting'
]
