/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Unified task status across executors.
 */
export type TaskStatus =
  | 'queued'
  | 'running'
  | 'success'
  | 'failed'
  | 'up_for_retry'
  | 'up_for_reschedule'
  | 'upstream_failed'
  | 'skipped'
  | 'deferred'
  | 'removed'
  | 'restarting'
