/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Temporal extent of the dataset, either a single instant or a period.
 */
export interface TemporalExtent {
  /**
   * Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). Start of period.
   Date of Validity in case of instant without duration.
   */
  start?: string | null

  /**
   * End date/time in ISO 8601 format. None if no time information is available.
   None if no time information is available or time reference is an instant. End of time period.
   */
  end?: string | null

  type: string
}
