/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Temporal extent of the dataset, either a single instant (no end) or a period.
 * Note: string max_length limits are intentionally added to help control LLM token usage.
 */
export interface TemporalExtent {
  /**
   * End date/time in ISO 8601 format. End of time period. IMPORTANT: end must be null for an insant Datestamp without duration.
   */
  end?: string | null

  /**
   * Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). Start of period. Single date of Validity in case of instant without duration.
   */
  start?: string | null
}
