/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Temporal extent of the dataset, either a single instant or a period.
 */
export interface TemporalExtent {
  /**
   * Start date/time in ISO 8601 format (e.g. '2023-01-01' or '2023-01-01T00:00:00'). Required when type='period', optional when type='instant'.
   */
  begin?: string | null

  /**
   * End date/time in ISO 8601 format. Required when type='period'. Use null if open-ended or unknown.
   */
  end?: string | null

  /**
   * Date/time in ISO 8601 format when type='instant'.
   */
  instant?: string | null

  /**
   * Either 'instant' (single date/time) or 'period' (date range). Use 'unknown' if no temporal information can be inferred.
   */
  type: string
}
