/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

/**
 * Payload sent by the frontend to save metadata to GeoNetwork and sync the title.
 */
export interface UpdateMetadataGnRequest {
  serialized_xml: string
  title: string
}
