/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RuleType } from '../models/rule-type';
import { RuleValue } from '../models/rule-value';
export interface UpsertRuleRequest {
  group_or_role: string;
  rule_type: RuleType;
  rule_value: RuleValue;
}
