# File included by gateway.yaml to set up the spring-gateway's routes
# target service URL's are defined in gateway.yaml (e.g. georchestra.gateway.services.<service>.target)

spring:
  cloud:
    gateway:
      routes:
      - id: backend
        uri: ${georchestra.gateway.services.backend.target}
        predicates:
        - Path=/backend/**
        filters:
          - RewritePath=/backend/(?<segment>.*),/$\{segment}
      - id: frontend
        uri: ${georchestra.gateway.services.frontend.target}
        predicates:
        - Path=/frontend/**
      - id: airflow
        uri: ${georchestra.gateway.services.airflow.target}
        predicates:
        - Path=/airflow/**
      - id: geoserver
        uri: ${georchestra.gateway.services.geoserver.target}
        predicates:
        - Path=/geoserver/**
