/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { requestBuilders } from '../../request-builders';

import { DagRunCollectionResponse } from '../../models/dag-run-collection-response';

export interface GetDagRunsAirflowDagsDagIdRunsGet$Params {
  dag_id: string;
  limit?: number;
}

export function getDagRunsAirflowDagsDagIdRunsGet(http: HttpClient, rootUrl: string, params: GetDagRunsAirflowDagsDagIdRunsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DagRunCollectionResponse>> {
  const rb = new requestBuilders(rootUrl, getDagRunsAirflowDagsDagIdRunsGet.PATH, 'get');
  if (params) {
    rb.path('dag_id', params.dag_id, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DagRunCollectionResponse>;
    })
  );
}

getDagRunsAirflowDagsDagIdRunsGet.PATH = '/airflow/dags/{dag_id}/runs';
