/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http'
import { Observable } from 'rxjs'
import { filter, map } from 'rxjs/operators'
import { StrictHttpResponse } from '../../strict-http-response'
import { requestBuilders } from '../../request-builders'

export interface GetDagRunLogsAirflowDagsDagIdRunsDagRunIdLogsGet$Params {
  dag_id: string
  dag_run_id: string
}

export function getDagRunLogsAirflowDagsDagIdRunsDagRunIdLogsGet(
  http: HttpClient,
  rootUrl: string,
  params: GetDagRunLogsAirflowDagsDagIdRunsDagRunIdLogsGet$Params,
  context?: HttpContext
): Observable<StrictHttpResponse<string>> {
  const rb = new requestBuilders(
    rootUrl,
    getDagRunLogsAirflowDagsDagIdRunsDagRunIdLogsGet.PATH,
    'get'
  )
  if (params) {
    rb.path('dag_id', params.dag_id, {})
    rb.path('dag_run_id', params.dag_run_id, {})
  }

  return http
    .request(rb.build({ responseType: 'text', accept: 'text/plain', context }))
    .pipe(
      filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
      map((r: HttpResponse<any>) => {
        return r as StrictHttpResponse<string>
      })
    )
}

getDagRunLogsAirflowDagsDagIdRunsDagRunIdLogsGet.PATH =
  '/airflow/dags/{dag_id}/runs/{dag_run_id}/logs'
