"""Tests for process-dag-generator callback URL construction."""

import importlib.util
import sys
import types
from pathlib import Path
from urllib.parse import parse_qs, urlparse

TRIGGER_OPERATOR_CALLS: list[dict] = []


def _load_module():
    """Load process-dag-generator.py without executing Airflow code.

    Also records the kwargs of every TriggerDagRunOperator instantiation into
    TRIGGER_OPERATOR_CALLS, so tests can inspect what create_dag() generates.
    """
    # Build minimal stubs so the module-level Airflow imports don't fail
    airflow_stub = types.ModuleType("airflow")

    class _FakeDAG:
        def __init__(self, *a, **kw):
            pass

        def __enter__(self):
            return self

        def __exit__(self, *a):
            return False

    airflow_stub.DAG = _FakeDAG  # type: ignore[attr-defined]

    trigger_stub = types.ModuleType("airflow.providers.standard.operators.trigger_dagrun")

    class _FakeTriggerDagRunOperator:
        def __init__(self, *a, **kw):
            TRIGGER_OPERATOR_CALLS.append(kw)

    trigger_stub.TriggerDagRunOperator = _FakeTriggerDagRunOperator  # type: ignore[attr-defined]

    for mod_name, stub in [
        ("airflow", airflow_stub),
        ("airflow.providers", types.ModuleType("airflow.providers")),
        ("airflow.providers.standard", types.ModuleType("airflow.providers.standard")),
        (
            "airflow.providers.standard.operators",
            types.ModuleType("airflow.providers.standard.operators"),
        ),
        ("airflow.providers.standard.operators.trigger_dagrun", trigger_stub),
    ]:
        sys.modules.setdefault(mod_name, stub)

    callback_stub = types.ModuleType("callback")
    callback_stub._dag_success_callback = lambda *a, **kw: None  # type: ignore[attr-defined]
    sys.modules.setdefault("callback", callback_stub)

    class _FakeDF:
        def to_dict(self, orient):
            return []

    class _FakeHook:
        def get_pandas_df(self, sql):
            return _FakeDF()

    utils_stub = types.ModuleType("utils")
    utils_stub.get_datafeeder_pg_hook = lambda: _FakeHook()  # type: ignore[attr-defined]
    utils_stub.normalize_nan = lambda value, default: default if value is None else value  # type: ignore[attr-defined]
    sys.modules["utils"] = utils_stub

    source = Path(__file__).parent.parent / "process-dag-generator.py"
    spec = importlib.util.spec_from_file_location("process_dag_generator", source)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


_module = _load_module()
_build_callback_url = _module._build_callback_url  # type: ignore[attr-defined]


class TestBuildCallbackUrl:
    def test_success_url_uses_backend_url_env(self, monkeypatch):
        monkeypatch.setenv("BACKEND_INTERNAL_URL", "http://my-backend:9000")
        url = _build_callback_url("/ingestion/process/dag_success", "abc-123", "my_table")
        parsed = urlparse(url)
        assert parsed.scheme == "http"
        assert parsed.netloc == "my-backend:9000"
        assert parsed.path == "/ingestion/process/dag_success"

    def test_success_url_contains_integrity_link_id(self, monkeypatch):
        monkeypatch.setenv("BACKEND_INTERNAL_URL", "http://datafeeder-backend:8000")
        url = _build_callback_url("/ingestion/process/dag_success", "abc-123", "my_table")
        qs = parse_qs(urlparse(url).query)
        assert qs["integrity_link_id"] == ["abc-123"]

    def test_success_url_contains_final_table_name(self, monkeypatch):
        monkeypatch.setenv("BACKEND_INTERNAL_URL", "http://datafeeder-backend:8000")
        url = _build_callback_url("/ingestion/process/dag_success", "abc-123", "my_table")
        qs = parse_qs(urlparse(url).query)
        assert qs["final_table_name"] == ["my_table"]

    def test_failure_url_points_to_dag_failure_endpoint(self, monkeypatch):
        monkeypatch.setenv("BACKEND_INTERNAL_URL", "http://datafeeder-backend:8000")
        url = _build_callback_url("/ingestion/process/dag_failure", "abc-123", "my_table")
        assert urlparse(url).path == "/ingestion/process/dag_failure"

    def test_default_backend_url_when_env_not_set(self, monkeypatch):
        monkeypatch.delenv("BACKEND_INTERNAL_URL", raising=False)
        url = _build_callback_url("/ingestion/process/dag_success", "abc-123", "my_table")
        assert url.startswith("http://datafeeder-backend:8000")


class TestCreateDagCallbackUrls:
    """Regression test for the internal-only callback paths generated by create_dag().

    Guards against a revert to the public /ingestion/process/dag_* endpoints, which
    the TestBuildCallbackUrl tests above would not catch since they call
    _build_callback_url directly with literal paths rather than exercising create_dag().
    """

    def test_generated_callback_urls_use_internal_path(self, monkeypatch):
        monkeypatch.setenv("BACKEND_INTERNAL_URL", "http://datafeeder-backend:8000")
        TRIGGER_OPERATOR_CALLS.clear()

        config = {
            "id": "abc-123",
            "data_id": "data-1",
            "metadata_id": "meta-1",
            "integrity_title": "Test",
            "staging_table_name": "staging_table",
            "final_table_name": "my_table",
            "schedule": "0 0 * * *",
            "integrity_transformation": None,
            "source_url": "http://example.com/data.csv",
            "source_import_type": "url",
            "source_layer": None,
            "source_protocol": None,
            "source_password_encrypted": None,
        }

        _module.create_dag(config)

        assert len(TRIGGER_OPERATOR_CALLS) == 1
        conf = TRIGGER_OPERATOR_CALLS[0]["conf"]
        assert (
            urlparse(conf["success_callback_url"]).path == "/internal/ingestion/process/dag_success"
        )
        assert (
            urlparse(conf["failure_callback_url"]).path == "/internal/ingestion/process/dag_failure"
        )
