name: build-docker-images.yml
on:
  push:
    branches:
      - main

jobs:
  build-database:
    runs-on: ubuntu-latest
    name: Build & push database
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build database
        run: |
          docker compose --profile datafeeder build database
          docker tag datafeeder-database:latest ghcr.io/georchestra/datafeeder/datafeeder-python-database:latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push database
        run: docker push ghcr.io/georchestra/datafeeder/datafeeder-python-database:latest

      - name: Push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ghcr.io/georchestra/datafeeder/datafeeder-python-database:latest ghcr.io/georchestra/datafeeder/datafeeder-python-database:${GITHUB_REF#refs/tags/}
          docker push ghcr.io/georchestra/datafeeder/datafeeder-python-database:${GITHUB_REF#refs/tags/}

  build-frontend:
    runs-on: ubuntu-latest
    name: Build & push frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        run: |
          docker compose --profile datafeeder build datafeeder-frontend
          docker tag datafeeder-datafeeder-frontend:latest georchestra/datafeeder-python-frontend:latest

      - name: "Log in to docker.io"
        if: github.repository == 'georchestra/datafeeder'
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Push frontend
        run: docker push georchestra/datafeeder-python-frontend:latest

      - name: Push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag georchestra/datafeeder-python-frontend:latest georchestra/datafeeder-python-frontend:${GITHUB_REF#refs/tags/}
          docker push georchestra/datafeeder-python-frontend:${GITHUB_REF#refs/tags/}

  build-backend:
    runs-on: ubuntu-latest
    name: Build & push backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend
        run: |
          docker build -f ./apps/backend/Dockerfile -t georchestra/datafeeder-python-backend:latest --target production .

      - name: "Log in to docker.io"
        if: github.repository == 'georchestra/datafeeder'
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Push backend
        run: docker push georchestra/datafeeder-python-backend:latest

      - name: Push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag georchestra/datafeeder-python-backend:latest georchestra/datafeeder-python-backend:${GITHUB_REF#refs/tags/}
          docker push georchestra/datafeeder-python-backend:${GITHUB_REF#refs/tags/}

  build-airflow:
    runs-on: ubuntu-latest
    name: Build & push airflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build airflow
        run: |
          docker build -f ./docker/Dockerfile.airflow -t georchestra/datafeeder-python-airflow:latest --target production .

      - name: "Log in to docker.io"
        if: github.repository == 'georchestra/datafeeder'
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_PASSWORD }}'

      - name: Push airflow
        run: docker push georchestra/datafeeder-python-airflow:latest

      - name: Push release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag georchestra/datafeeder-python-airflow:latest georchestra/datafeeder-python-airflow:${GITHUB_REF#refs/tags/}
          docker push georchestra/datafeeder-python-airflow:${GITHUB_REF#refs/tags/}
