/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { requestBuilders } from '../../request-builders';

import { SettingsResponse } from '../../models/settings-response';

export interface GetSettingsSettingsGet$Params {
}

export function getSettingsSettingsGet(http: HttpClient, rootUrl: string, params?: GetSettingsSettingsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsResponse>> {
  const rb = new requestBuilders(rootUrl, getSettingsSettingsGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsResponse>;
    })
  );
}

getSettingsSettingsGet.PATH = '/settings/';
